### ISSUE TITLE
Old version on cpan

### ISSUE THREAD

**Issue by AlexK-IL** [mkamensky/Text-Bidi#4]
Hello Moshe, when I'm looking at:
https://metacpan.org/release/Text-Bidi
I see that the latest version is 2.11, but according to your [README](https://github.com/mkamensky/Text-Bidi/blob/master/README.mkdn) file it should be 2.12.
Can you release the newer version?
Thank you.

**Comment by mkamensky** [comment]
Hi Alex,

It seems I just changed the version number so I know what version am I working on. There are no essential changes there from 2.11

**Comment by mkamensky** [comment]
I did find some local changes to the bidi plugin, which I just uploaded.

**Comment by AlexK-IL** [comment]
Okay thank you, so I'll close this issue.

**Comment by mkamensky** [comment]
I actually just uploaded the changes to cpan, since the modifications to the plugin might be useful. Thanks for the feedback.

**Comment by AlexK-IL** [comment]
I see, I'll check it out!
I'm a little bit confused about a few things.
In this project do you maintain both the perl module Text::Bidi and the urxvt plugin (which is at [misc/bidi](https://github.com/mkamensky/Text-Bidi/blob/master/misc/bidi) if I'm not wrong)?
And how do you upload to cpan? Is it automatic when you push to git or do you manually upload it?
For you information, I have uploaded your plugin to archlinux's package repository to make it easier to install for fellow archers. The packages are [perl-text-bidi](https://aur.archlinux.org/packages/perl-text-bidi/) and [urxvt-bidi](https://aur.archlinux.org/packages/urxvt-bidi/).

**Comment by mkamensky** [comment]
Yes, they are part of the same project. I should probably put the plugin in some plugin repo, but since for me the purpose of the module is to be the engine for the plugin, I think of them as part of the same.

The upload to cpan is via Dist::Zilla, which also uploads to github, but I also push to github intermediate changes.

Thanks for uploading to arch, I might need to install it soon...

**Comment by AlexK-IL** [comment]
No problem :)
I need to update the versions now though.
I wonder if I should use the git repository as the source for the packages. Right now I'm using https://cpan.metacpan.org/authors/id/K/KA/KAMENSKY/$_dist-$pkgver.tar.gz for perl-text-bidi and https://api.metacpan.org/source/KAMENSKY/Text-Bidi-$pkgver/misc/bidi for urxvt-bidi.
