### ISSUE TITLE
urxvt-bidi toggle option doesn't work

### ISSUE THREAD

**Issue by zelhar** [mkamensky/Text-Bidi#7]
Shalom Moshe,

I am using your urxvt-bidi plugin on on arch linux. It looks like the options to toggle it on or off as well as to start with disabled don't work. If I have bidi on the perl-ext-common list, urxvt will start with the bidi enabled and it cannot be disabled.

Thanks for the good work.

----
This is what I have in my .Xresources:

URxvt.bidi.enabled:	  0
URxvt.keysym.F12:    perl:bidi: show
URxvt.keysym.M-C-b:    perl:bidi: toggle show
!URxvt.keysym.A-0x0062:    perl:bidi toggle show
!URxvt.keysym.C-0x0062:    perl:bidi toggle show
!line above is supposed to define Ctrl-B as a map to toggle bidi support on/off
!URxvt.bidi.LRE: \[([]
!URxvt.bidi.PDF: \[)]]
URxvt.bidi.LRE: \\\\[([]
URxvt.bidi.PDF: \\\\[)\\]]
urxvt-vimh.bidi.par: true
urxvt-vimh.cursorUnderline: true
urxvt-vimh.bidi.ParReset: ^\\s*$|^\\\\begin|^\\\\\\[
urxvt-vimh.bidi.ParResetAfter: ^\\\\end|\\\\\\]$

**Comment by mkamensky** [comment]
@zelhar Hi and sorry for the delay. I do not recall providing an option to disable the plugin, did I suggest it somewhere?

**Comment by zelhar** [comment]
Hi @mkamensky 
Maybe it's a misunderstanding? There is the bidi add-on at the arch linux AUR repos. The install is broken at least for my system. The info links to your perl addon. I suppose somebody wrote another extension based on yours? 
https://aur.archlinux.org/packages/urxvt-bidi/
https://bitbucket.org/sterlingcamden/urxvt-bidi/src

**Comment by mkamensky** [comment]
@zelhar the first link is my package (slightly behind the latest version, but not a big difference). The second one is not mine, though it does seem to be based on an extremely old version of the same. I would not use it.
