### ISSUE TITLE
Package build error

### ISSUE THREAD

**Issue by rand-asswad** [mkamensky/Text-Bidi#8]
I'm having problems installing this package. I tried everything but I get the same error from the package build.
`ERROR: A failure occurred in build(). Aborting...`

I first thought the problem was that I didn't have **perl-extutils-pkgconfig** but the problem persisted even after I installed it. I also tried debugging **private.c** myself, but I couldn't resolve the problem.
I'm installing this package as a dependency for **urxvt-bidi**. Any help would be appreciated.

Here is the complete [PKGBUILD output](https://github.com/mkamensky/Text-Bidi/files/1775829/error_build.log).

Thank you in advance.

**Comment by mkamensky** [comment]
Hi, sorry for delayed reply. I think the issue is with the libfribidi version, you are using >=1.0, right? The interface has changed, I had no time to upgrade the module yet, so at this point, version 0.19.7 is required

**Comment by gregoa** [comment]
Ok, it turns out that (1) cleaning private.c (as in swig-clean in Makefile.PL) and (2) apply Petr's patch from https://rt.cpan.org/Public/Bug/Display.html?id=124618 allows building with passing tests against fribidi >= 1.0. (Dots connected by @ntyni)

**Comment by mkamensky** [comment]
This is great, thank you very much!


* gregor herrmann <notifications@github.com> [30/07/18 10:40]:

**Comment by mkamensky** [comment]
Just uploaded a fix by including the deprecated interface. Thanks for the help and sorry for the long delay.
